### ISSUE TITLE
Bolt 12 support

### ISSUE THREAD

**Issue by Sjors** [dennisreimann/bitcoindevlist.com#103]
In order to support [BOLT 12](https://bolt12.org) offers - for single as well as recurring - I suggest adding one or two fields to the JSON:

1. `bolt12_single`
2. `bolt12_recurring`

The best practice then would be to create two offers, without an amount. Like so in [c-lightning](https://lightning.readthedocs.io/lightning-offer.7.html):

```
lightning-cli offer any "Open source development donation" "Shady Super-Coder" "open-source-single-donation"
lightning-cli offer any "Open source development monthly donation" "Shady Super-Coder" "open-source-monthly-donation" null null null 1month
```
 
The site could then display these somewhere (as plain text for now, QR when mobile wallets support it).

On the donator side IIUC they use `lightning-cli createinvoicerequest [bolt12]`. This method is as yet undocumented, so yolo. I assume it returns an invoice that you then pay.

There's some discussion about making this flow more automated: https://github.com/lightningnetwork/lightning-rfc/pull/798#discussion_r671868840

Initially perhaps `bolt12_single` is a good start, since recurring payments are very tedious. But they would be really awesome once there.

**Comment by renepickhardt** [comment]
Concept ACK

**Comment by Sjors** [comment]
Fwiw, I actually received a donation this way: https://twitter.com/rusty_twit/status/1420565586552057862

**Comment by dennisreimann** [comment]
@Sjors Can you open a PR with those properties added for your profile? I can take care of displaying that info then :)

**Comment by Sjors** [comment]
@dennisreimann thanks! Done in #104

**Comment by dennisreimann** [comment]
I think the UX or at least description can be improved, but let's go with this as a start …

![bolt12](https://user-images.githubusercontent.com/886/127744843-75b47392-e0bd-4725-a6c7-b1d1673daf70.png)

**Comment by Sjors** [comment]
Nice! A distinction between fiat and lightning could make sense, maybe just add $ and a lightning bolt.
