### ISSUE TITLE
SpaceBox question

### ISSUE THREAD

**Issue by alevchuk** [dennisreimann/bitcoindevlist.com#110]
https://github.com/dennisreimann/bitcoindevlist.com/blob/933f7e2bf137fecb9e0dc2705b7fd231b53a774b/donatees/chimezie-chuta.json#L7 

Looking at the project https://trustonailende.com/spacebox-bitcoin-node-kit/ how would the network work? It's not mentioned on the website yet an important question to address up front. Can't ask on Twitter because the account got censored :/

**Comment by dennisreimann** [comment]
@chuta can you answer this?
