### ISSUE TITLE
ln address does not appear to responsively change size

### ISSUE THREAD

**Issue by secondl1ght** [dennisreimann/bitcoindevlist.com#120]
I was testing locally and I added a lightning address to my profile, others have a shorter address that seems to fit inside the element. Mine is a bit longer and the element does not seem to responsively adjust size and the address overflows. See screenshot:

![image](https://user-images.githubusercontent.com/85003930/142806606-9be2b928-bb0b-47f7-999d-9b6d4d3b3ede.png)

**Comment by dennisreimann** [comment]
Thanks, fixed it!
