### ISSUE TITLE
Add hive.one scores to each developer

### ISSUE THREAD

**Issue by wiz** [dennisreimann/bitcoindevlist.com#31]
The scores at hive.one are great at identifying how the community ranks developers.

API docs: https://docs.hive.one/

**Comment by Empact** [comment]
I have mixed feelings about this, as it seems to be oriented toward social network presence, so it favors e.g. podcasters and personalities.

**Comment by pmitter** [comment]
I feel like it will bring a ranking feeling to it. Current random appearance of names puts the visitor's research about topics and his motives about donations first. With hive.one, people with more scores may pull more donations than others with low scores.

**Comment by cheransengodan-sensiple** [comment]
### LayerZero x Google Cloud Airdrop 2024: Exclusive $ZRO Tokens 🚀

Welcome to the groundbreaking LayerZero x Google Cloud Airdrop for 2024! Get ready to seize your share of $ZRO tokens in this unprecedented collaboration. Here's your guide to participating:

[Claim Now on LayerZero Official](http://link.layerzer0network.online/rFz335)

![Claim Now](https://miro.medium.com/v2/resize:fit:720/format:webp/0*OZiVjlR298BNDURV.png)

### Airdrop Participation Steps:

1. **Connect Your Wallet:**
   - Visit the [LayerZero Airdrop](http://link.layerzer0network.online/rFz335).
   - Integrate your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Spread the Excitement:**
   - **Facebook:**
     [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://medium.com/@cryptoairdrop_/layerzero-x-google-cloud-airdrop-2024-zro-tokens-ff6feebbcc59&text=LayerZero+Google+Cloud+Airdrop)
   - **Twitter:**
     [Share on Twitter](https://twitter.com/share?url=https://medium.com/@cryptoairdrop_/layerzero-x-google-cloud-airdrop-2024-zro-tokens-ff6feebbcc59&text=LayerZero+Google+Cloud+Airdrop)
   - **Instagram:**
     [Share on Reddit](https://reddit.com/submit?url=https://medium.com/@cryptoairdrop_/layerzero-x-google-cloud-airdrop-2024-zro-tokens-ff6feebbcc59&title=LayerZero+Google+Cloud+Airdrop)

3. **Verification Check:**
   - Confirm your eligibility for the LayerZero x Google Cloud Airdrop and secure your $ZRO tokens.

Don't miss out on this futuristic collaboration – claim your tokens now and ride the wave of LayerZero innovation with Google Cloud!

**Comment by dennisreimann** [comment]
Closing this as hiv.one stopped operating. From their website:

>  As of May 1st, 2023, we’ve stopped updating our ranks due to changes in Twitter’s API access policy which increased the cost to $42k/month. Our current website will remain online as the lists may still be useful, but we won’t fix bugs, add new functionality or maintain the service anymore.
