### ISSUE TITLE
LNURL-pay support

### ISSUE THREAD

**Issue by m00ninite** [dennisreimann/bitcoindevlist.com#95]
This is less of an "issue" or a "feature request" and more of an "I'd like to build this and looking for feedback".

I'm cooking up an idea to help grow lightning adoption, as well as get some sats into developers' hands. It basically happens in two parts:

1) Add lnurl-pay to bitcoindevlist.com, this can just be another field in the existing donatee json files.
2) Add features to existing popular Telegram bots (eg: Cheeserobot or lntxbot) that randomly selects a developer daily, and spits out their lnurl-pay address. The bots could pull the info directly from github for now, maybe build a proper API for the site in the future.

Interesting? Stupid? Inappropriate for the main site? I'd love to hear your thoughts. :smiley:

**Comment by Fittiboy** [comment]
Bumping this with an update: The [Lightning Address standard](https://lightningaddress.com) is gaining adoption _fast_.
A lightning address, like tips@fitti.io, could easily be displayed as a separate field instead of an lnurl-pay link. Would be trivials for bots to fetch that.

**Comment by dennisreimann** [comment]
@Fittiboy Sounds good – let's approach it like we did in #103: Add a `lnaddr` field with your Lightning address to your JOSN and I'll integrate it on the frontend side :)

**Comment by Fittiboy** [comment]
@dennisreimann Done, #109. Thanks! :+1:
